### ISSUE TITLE
Go version 1.21 or 1.21.0 is not getting installed.

### ISSUE THREAD

**Issue by kumvijaya** [drewgonzales360/goenv#15]
Thanks for this good tool.
If I try to install go version 1.21.0 or 1.21, I get an error as release not found.

```
goenv install 1.21
😥 could not find release
could not dowload go - response code: 404 Not Found
```
Checked https://go.dev/dl/.
Maybe because of this whole version '1.21' (MAJOR.MINOR only format) is not present in the archived list of versions. The list has 1.21.0.
But other whole versions like '1.19', '1.20', etc present in the list (MAJOR.MINOR only format).

Please see if you can handle and fix this.

Thanks

**Comment by ankitcharolia** [comment]
@kumvijaya kindly try this one: https://github.com/ankitcharolia/goenv

**Comment by drewgonzales360** [comment]
Shoot, sorry. I made the [fix back when it came out](https://github.com/drewgonzales360/goenv/commit/2b4d348af05f2de6d0bf7dd167d459567d3320ed), but never cut a release for it. I just cut [v0.3.0](https://github.com/drewgonzales360/goenv/releases/tag/v0.3.0)
